# Generated by Django 3.0.4 on 2020-03-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200324_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
